# Generated by Django 3.1.1 on 2020-10-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameline',
            name='odds_source',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
