# Generated by Django 3.1.1 on 2020-09-30 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('gameweek', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='api.soccerteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='api.soccerteam')),
            ],
        ),
        migrations.CreateModel(
            name='GameLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField()),
                ('away', models.IntegerField()),
                ('tie', models.IntegerField()),
                ('pulled_on', models.DateTimeField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.fixture')),
            ],
        ),
    ]
